name: Admin Docker Dev Image CI

on:
  push:
    branches: [ "developer" ]
  pull_request:
    branches: [ "developer" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t luffedeluxe/bookmycampadmin:dev -f Dockerfile
    - name: Push Image to DockerHub
      run: |
       docker login -u luffedeluxe -p ${{ secrets.DOCKER_HUB_TOKEN }}
       docker push luffedeluxe/bookmycampadmin:dev
